### ISSUE TITLE
Non minified blog?

### ISSUE THREAD

**Issue by joeseeley** [leonardovilarinho/leonardovilarinho.github.io#1]
I was trying out your Vue plugin, vue-acl.  It looks pretty cool.  I noticed that you have put some help documentation together at https://leonardovilarinho.github.io/vue-acl/.  That's great, so I thought I could clean up the writing a bit for you, but there is only the minified version checked in.

**Comment by leonardovilarinho** [comment]
Hello there,

you can do clone `vue-acl` repository and edit `docs` [branch](https://github.com/leonardovilarinho/vue-acl/tree/docs). When you send a PR, I can execute build and add in production.
